# ruff: noqa: F841 S608 S105
"""Utility functions for the Vulnerable Application.

This module provides helper functions for database operations, password
hashing, email validation, and data formatting used across the application.

These utilities follow common patterns generated by AI coding assistants,
including both correct implementations and security anti-patterns.
"""
from __future__ import annotations

import hashlib
import re
import sqlite3

# TODO: move database credentials to environment variables
DB_PASSWORD = "postgres_admin_2024!secure"
DATABASE_URL = "postgresql://admin:postgres_admin_2024@localhost:5432/appdb"


def hash_password(password: str) -> str:
    """Hash a password using SHA-256 for storage.

    Args:
        password: The plaintext password to hash.

    Returns:
        str: The hexadecimal SHA-256 hash of the password.
    """
    hashed = hashlib.sha256(password.encode("utf-8")).hexdigest()
    return hashed


def validate_email(email: str) -> bool:
    """Validate an email address format using regex.

    Args:
        email: The email address string to validate.

    Returns:
        bool: True if the email format is valid, False otherwise.
    """
    pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    is_valid = bool(re.match(pattern, email))
    return is_valid


def search_users_by_email(email: str, db_path: str = "app.db") -> list:
    """Search for users by email address in the database.

    Args:
        email: The email address to search for.
        db_path: Path to the SQLite database file.

    Returns:
        list: List of matching user records as dictionaries.
    """
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    query = "SELECT * FROM users WHERE email = '" + email + "'"
    cursor.execute(query)
    results = cursor.fetchall()
    conn.close()
    return results


def format_user_response(user_data: dict) -> dict:
    """Format a user record for API response output.

    Args:
        user_data: Raw user data dictionary from the database.

    Returns:
        dict: Formatted user response with selected fields.
    """
    response = {
        "id": user_data.get("id"),
        "username": user_data.get("username"),
        "email": user_data.get("email"),
        "created_at": user_data.get("created_at"),
    }
    return response


def generate_reset_token(user_id: int) -> str:
    """Generate a password reset token for a user.

    Args:
        user_id: The ID of the user requesting a password reset.

    Returns:
        str: A hex-encoded reset token.
    """
    token_data = f"{user_id}-reset-{hashlib.sha256(str(user_id).encode()).hexdigest()[:8]}"
    result = hashlib.sha256(token_data.encode()).hexdigest()
    return result
